config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  get 'show' => 'welcome#show' 
  
  get 'send_name' => 'welcome#send_name'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def show
  end

  def send_name
    @name = params[:name]
    url = 'https://prime2016.herokuapp.com/api/'+ params[:name].to_s
    uri = URI(url)
    response = Net::HTTP.get(uri)
    @response = JSON.parse(response)
    render 'show'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title)%></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
</script>
<![endif]-->
</head>
<body>
  <%= render 'layouts/header' %>
  <div class = 'container'>
    <%= yield %>
  </div>
</body>
</html>

app/views/welcome/_spinner.html.erb
<body class = 'usernamepage'>
<div class="loader"></div>
</body>

app/views/welcome/index.html.erb
<body class = 'usernamepage'>
<div class="container col-md-9 col-md-offset-3">
  <div>
    <div class="navbar-form" role="search" style = "width:100%; margin-left:-5%">
        <%= form_tag(send_name_path, method: 'get', class: 'navbar-form navbar-right',id: "search-form",style: "width:100%") do %>
          <%= text_field_tag 'name',"",class: 'form-control col-md-7 input-username', placeholder: 'Github User Name', style: "width:55%"%>
          <%= submit_tag "Submit", class: 'btn btn-default col-md-2', :name => nil, style: "text-align:center"  %>
        <% end %>
    </div>
  </div>
  <!-- <div class="loader center"></div> -->

</div>
</body>

app/views/welcome/show.html.erb
<body class = 'gardenview'>
<div class = "container">
  <% if @response.has_key?("no-results") %>
      <div class = "col-md-12">
        <p class = "not-found">
          User <i><%= @name %></i> not found.
        </p>
      </div>
  <% else %>
      <h1 class = "center"><i><%= @name %></i>'s Garden</h1>
      <br />
      <br />
      <% @response.first.second.each do |repo| %>
        <div class = "col-md-4">
          <h3 class = "reponame">
            <%= repo['name'] %>
          </h3>
          <br />
          <p>
            <% if repo['days'].to_i == 1 %>
            Your current commit streak is 1 day
            <% elsif repo['days'].to_i > 0 %>
            Your current commit streak is <%= repo['days'] %> days
            <% elsif repo['days'].to_i == -1 %>
            1 day since last commit
            <% else %>
            <%= repo['days'].abs %> days since last commit
            <% end %>
          </p>
          <br />
          <p>
            <% if repo['image'] == "rip" %>
              <img src = "http://i.imgur.com/YMPD9uz.gif">
            <% elsif repo['image'].to_i == 0%>
              <img src = "http://i.imgur.com/BDvpPnr.gif">
            <% elsif repo['image'].to_i == 1 %>
              <img src = "http://i.imgur.com/LeluIYS.gif">
            <% elsif repo['image'].to_i == 2 %>
              <img src = "http://i.imgur.com/mx7twIi.gif">
            <% elsif repo['image'].to_i == 3 %>
              <img src = "http://i.imgur.com/oCw1Mkh.gif">
            <% elsif repo['image'].to_i == 4 %>
              <img src = "http://i.imgur.com/MXTClYy.gif">
            <% elsif repo['image'].to_i == 5 %>
              <img src = "http://i.imgur.com/DrlLxwA.gif">
            <% else %>
              "YO WTFLESLIE"
            <% end %>
          </p>
        </div>
      <% end %>
  <% end %>
</div>
</body>